// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwqksitlfjbytjeahvvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cWtzaXRsZmpieXRqZWFodnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDQzNTMsImV4cCI6MjA2OTU4MDM1M30.VNMImo33UjwDPFly4dJw3TfzAcyA5N_m_oEnBnBZ9rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});